### ISSUE TITLE
Create three page website

### ISSUE THREAD

**Issue by krisjowen** [krisjowen/yubaba#1]
**User stories**

As a site visitor, I want to be able to see details about the band and to contact them with details of any potential bookings.

As the band, I want to show images of how we look and present a profile

**Acceptance criteria**

- [ ] High quality image of band available
- [ ] Booking form in place
- [ ] Profile of band and its members

**Tasks**

- [ ] Create hero image on home page
- [ ] Have contact ctas on each page
- [ ] Utilise cards on about page to showcase members and show images
